[tools]
node = "22"
pnpm = "10.12"
deno = "2"
bun = "latest"

[tasks.lint]
run = "pnpm lint"

[tasks.pnpm_install]
run = "pnpm install --frozen-lockfile"

[tasks.build]
run = "pnpm build"

[tasks.test]
run = "pnpm test"

[tasks.test_unit]
run = "pnpm run test:unit"

[tasks.test_performance]
run = "pnpm run test:performance"

[tasks.qa]
run = ["pnpm lint", "pnpm test", "pnpm build"]

[tasks.typedoc_build]
run = "pnpm typedoc --out docs-temp"

# Deno tasks
[tasks.deno_check]
run = "deno task check"

[tasks.deno_test]
run = "deno task test"

[tasks.deno_lint]
run = "deno task lint"

[tasks.deno_fmt]
run = "deno task fmt"

[tasks.deno_fmt_check]
run = "deno task fmt:check"

[tasks.deno_publish]
run = "deno task publish"

[tasks.deno_publish_dry]
run = "deno publish --dry-run"

[tasks.deno_publish_release]
run = "deno publish"

# Bun smoke test
[tasks.bun_test]
run = "bun test tests-bun"

# Integration test (Node)
[tasks.test_integration]
run = "pnpm exec tsx tests/integration/usage.test.ts"

[tasks.publish_npm]
run = "pnpm publish --access public --no-git-checks"
