name: Bun Smoke Test

on:
  pull_request:
    branches:
      - main

jobs:
  bun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup tools via mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: mise run pnpm_install

      - name: Run Bun tests (smoke)
        run: mise run bun_test
