name: Integration Test with Built Package

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup tools via mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: mise run pnpm_install

      - name: Build the library
        run: mise run build

      - name: Run integration test
        run: mise run test_integration
