name: Publish to JSR

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Deno check
        run: deno task check

      - name: Deno test (smoke)
        run: deno task test

      # NOTE: Set repository secret JSR_TOKEN to your JSR auth token.
      # See https://jsr.io/docs/publishing for instructions.
      - name: Publish to JSR
        run: deno publish --token "${{ secrets.JSR_TOKEN }}"
